### ISSUE TITLE
Dissemination: blog post with step by step application of pipelines

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#104]
One of the big motivators for pipelines was scikit-learn pipelines and the fact that nothing like this was available in R. That still remains true. Since there are still new blog posts coming out that talk about the virtues of pipelines in Python, it only seems natural to create a mirror blog post describing how exactly the same operations can be performed with sl3:

https://www.kdnuggets.com/2017/12/managing-machine-learning-workflows-scikit-learn-pipelines-part-1.html

**Comment by nhejazi** [comment]
@osofr This is an awesome idea! I'd be happy to help with this (indeed, just translating the linked blog post to R using `sl3`, at least for now?).  It would make a great addition to [Mark's new blog](https://vanderlaan-group.github.io/post/), on GitHub [here](https://github.com/vanderLaan-Group/vanderLaan-Group.github.io/tree/sources/content/post)! (I'd also likely re-post / initially post it on my own (unpopular) blog [here](https://blog.nimahejazi.org/).)

**Comment by osofr** [comment]
I think translating the same thing into R is a great start. I am sure we will discover bugs / areas to improve with `sl3` as we do that. So still should be a useful exercise for us.

**Comment by nhejazi** [comment]
@osofr @jeremyrcoyle @podTockom ---
I've made a quick facsimile of the blog post on scikit-learn, linked above. A working draft of the post is available [here](https://blog.nimahejazi.org/posts/pipelines-sl3/) on my own blog, and the source Rmd is [here](https://raw.githubusercontent.com/nhejazi/almost-surely/master/content/posts/pipelines-sl3.Rmd). (_Aside_: It'd be nice to remove the h2o bits eventually to make the content of the post more minimal / accessible through just `sl3`). Also, feel free to make PRs directly against the post if so desired.

It would be great to get feedback / input / corrections. Once it's complete, we can post to Mark's Targeted Learning blog and circulate via Twitter and Medium as well. Additionally, I think we should probably write a series of blog posts on `sl3` over the coming months.

**Comment by nhejazi** [comment]
The blog post is now live: https://tlverse.org/2018/04/08/sl3_demo/

Closing this now but please re-open and/or edit the blog post (https://github.com/tlverse/tlverse.org/blob/master/content/post/sl3_demo.Rmd) as needed.
