### ISSUE TITLE
Learner Wishlist

### ISSUE THREAD

**Issue by jeremyrcoyle** [tlverse/sl3#114]
- [x] gam (via [`mgcv`](https://cran.r-project.org/web/packages/mgcv/index.html))
- [x] ranger
- [ ] screening methods (see `SuperLearner::listWrappers()` for a list). I think Sara also has a bunch.
- [x] svm
- [x] mars (via [`earth`](https://cran.r-project.org/web/packages/earth/index.html))
- [x] rpart
- [x] caret
- [x] gbm
- [x] hal (via [`hal9001`](https://github.com/jeremyrcoyle/hal9001))
- [x] polynomial splines (via [`polspline`](https://cran.r-project.org/web/packages/polspline/index.html))

**Comment by nhejazi** [comment]
See #127, #132, #133 for implementations ranger, svm, and rpart.

**Comment by nhejazi** [comment]
#220 adds `earth`, `polymars`/`polyclass`, and `gbm`
