### ISSUE TITLE
Handle character vectors in Tasks

### ISSUE THREAD

**Issue by nhejazi** [tlverse/sl3#121]
Currently, running a simple Super Learner with `sl3` on the included `cpp_imputed` data set with the full set of variables causes an issue due to the presence of variables of class `character`. To resolve this, `sl3` should have a built-in function that coerces variables from `character` to `factor` (and I guess back to `character` when displaying results?), probably as part of the `sl3_Task$new()` method. As an example, the following code -- courtesy of @jeremyrcoyle -- implements a new function `char_to_factor` that handles this coercion on a given input data set.

```
library(sl3)
library(data.table)
set.seed(37942)
data(cpp_imputed)

setDT(cpp_imputed)
char_to_factor <-function(data) {
  classes <- sapply(data, data.class)
  char_cols <- names(classes)[which(classes == "character")]
  set(data, , char_cols, data[,lapply(.SD, as.factor), .SDcols = char_cols])
}
char_to_factor(cpp_imputed)

task <- sl3_Task$new(data = cpp_imputed, covariates = colnames(cpp_imputed)[-6], outcome = "bmi")
lrn_mean <- Lrnr_mean$new()
lrn_glm <- Lrnr_glm$new()
lrn_rf <- Lrnr_randomForest$new()
lrn_sl <- Lrnr_sl$new(learners = list(lrn_mean, lrn_glm, lrn_rf), metalearner = Lrnr_nnls$new())
sl_trained <- lrn_sl$train(task)
```

**Comment by jeremyrcoyle** [comment]
Resolved in https://github.com/tlverse/sl3/pull/200
