### ISSUE TITLE
wrapping superleaner in Lrnr_cv

### ISSUE THREAD

**Issue by jamesfalter** [tlverse/sl3#128]
I ran into the following error trying to cross-validate a Superlearner by wrapping it in Lrnr_cv:

Error in .subset2(public_bind_env, "initialize")(...) : 
  (list) object cannot be coerced to type 'logical'
In addition: Warning message:
In all(learners_trained) : coercing argument of type 'list' to logical

### CODE USED
# setup parameters for superlearner
library(sl3)
data(cpp_imputed)
# only looking at continuous covariates in cpp_imputed
classes <- sapply(cpp_imputed, data.class)
indx.char <- which(classes == "character")
all.vars <- names(cpp_imputed)
cpp_edited <- select(cpp_imputed, all.vars[-indx.char])

# create superlearner then pipe into cross-validation learner
learner.list <- as.list(c(lrnr_glm, lrnr_mean, lrnr_RF, lrnr_xgboost, lrnr_glm_fast))
metalearner <- make_learner(Lrnr_nnls)
SL <- Lrnr_sl$new(learners = learner.list, metalearner = metalearner)
slcv_pipe <- make_learner(Pipeline, SL, Lrnr_cv)

**Comment by jeremyrcoyle** [comment]
Thanks for submitting this

**Comment by jeremyrcoyle** [comment]
This has been resolved (unclear of the PR). A MRE:

```
library(sl3)
library(tidyverse)
data(cpp_imputed)
classes <- sapply(cpp_imputed, data.class)
indx.char <- which(classes == "character")
all.vars <- names(cpp_imputed)
cpp_edited <- select(cpp_imputed, all.vars[-indx.char])
lrnr_glm <- make_learner(Lrnr_glm)
lrnr_mean <- make_learner(Lrnr_mean)
learner.list <- as.list(c(lrnr_glm, lrnr_mean))
metalearner <- make_learner(Lrnr_nnls)
SL <- Lrnr_sl$new(learners = learner.list, metalearner = metalearner)
cvsl <- make_learner(Lrnr_cv, SL)
task <- make_sl3_Task(cpp_edited, outcome="haz", covariates=c("bmi","waz"))
cvsl_fit <- cvsl$train(task)
cvsl_fit$cv_risk(loss_squared_error)
```

See also the helper function `sl3::CV_lrnr_sl`
