### ISSUE TITLE
Combining Lrnr_cv and Lrnr_sl

### ISSUE THREAD

**Issue by ncmagnus** [tlverse/sl3#129]
When attempting to use the data cpp_imputed in library sl3, I ran into a bug when training a super learner that combines Lrnr_sl and Lrnr_cv. The error appears to be internal, causing an issue to the .private function $dependencies. Specifically, the argument to which function is not logical. The code that creates the error is displayed below:

```r
##Recreate Error with as little code as possible ##
library(sl3)
data(cpp_imputed)
set.seed(37942)
task_error <- make_sl3_Task(data = cpp_imputed, covariates <- c("wtkg", "htcm", "lencm", "waz", "haz", "whz", "baz", "siteid", "sexn") ,
                      outcome = "smoked", outcome_type="binomial")
#make two simple learners
lrnr_glm_bin <- make_learner(Lrnr_glm)
lrnr_glm_mean_bin <- make_learner(Lrnr_mean)
#attempt to combine Lrnr_sl and Lrnr_cv
cv_stack_s <- Lrnr_cv$new(Lrnr_sl$new(learners = list(lrnr_glm_bin, lrnr_glm_mean_bin),
                                      metalearner=Lrnr_nnls$new()), V = 10)
cv_fit_s <- cv_stack_s$train(task_s)
```

I know this to not be an issue with my code since a class of students got the exact same error on this portion of our homework under the supervision of Nima @nhejazi . Here are some of the other students who got the same issue:

@rachaelvphillips
@yue_you
@WaverlyWei
@jamesfatler
@lmmontoya

Thank you,
Nina

**Comment by gshan1991** [comment]
I ran into this issue as well.

**Comment by nhejazi** [comment]
Thanks for submitting this. As this reports the same bug as in #128, I'm closing this. Please keep an eye out on that issue for the solution to be implemented.
