### ISSUE TITLE
outcome_type not documented

### ISSUE THREAD

**Issue by biohackVV** [tlverse/sl3#130]
Hi in:
https://sl3.tlverse.org/reference/sl3_task

the valid values for outcome_type, is not documented. After searching on internet, it seems there is no information in any webpage indexed by google.  It might be necessary to add which values are acceptable, i.e. "continuous", "binomial", etc....

**Comment by jeremyrcoyle** [comment]
Thanks

**Comment by kmishra9** [comment]
Going to bump this -- would be helpful to have this documented somewhere in the help section.

**Comment by nhejazi** [comment]
This has been documented in `Variable_Type` and `default_metalearner`.
