### ISSUE TITLE
sl3 seems like mlr

### ISSUE THREAD

**Issue by harryprince** [tlverse/sl3#138]
`sl3` seems like `mlr`, maybe merge project to mlr?
And `delayed` seems like `future` package?

https://mlr-org.github.io

**Comment by nhejazi** [comment]
Thanks for bringing this to our attention. We were wondering --- did you have an actual question? Of course, we're aware of both [`mlr`](https://github.com/mlr-org/mlr) and [`future`](https://github.com/HenrikBengtsson/future) given that

1. we mention `mlr` in the first paragraph of the [introductory vignette](https://sl3.tlverse.org/articles/intro_sl3.html) of the [`sl3` project](https://sl3.tlverse.org), and
2. we've sat down for a face-to-face meeting with the author of [`future`](https://github.com/HenrikBengtsson/future), who generously spent his time in helping us to make [`delayed`](https://delayed.tlverse.org) possible.

I'm going to go ahead and close this. If you feel that there's some way you'd like to help out this project, we'd recommend opening up an issue with a more substantial/concrete suggestion.
