### ISSUE TITLE
Add release tag(s) for sl3 repository

### ISSUE THREAD

**Issue by krinsman** [tlverse/sl3#140]
I would like to make a [conda package](https://www.slideshare.net/continuumio/revolutionizing-data-science-package-management-with-conda) for `sl3`. 

I understand that `sl3` is currently in beta testing, but it would be possible to update the conda package as `sl3` becomes more mature.

According to [this issue on GitHub](https://github.com/conda/conda/issues/6674), in order to make a conda package for `sl3`, it is necessary for the repository to have at least one release tag.

Here is the output of `conda skeleton cran https://github.com/tlverse/sl3`:

```
conda skeleton cran https://github.com/tlverse/sl3

Tip: install CacheControl and lockfile (conda packages) to cache the CRAN metadata
Fetching metadata from https://cran.r-project.org
Parsing input package https://github.com/tlverse/sl3:
.. name: sl3 location: https://github.com/tlverse/sl3 new_location: /Users/krinsman/r-sl3
Making/refreshing recipe for sl3
Cloning into '/opt/anaconda/anaconda3/conda-bld/skeleton_1525233478806/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

fatal: No names found, cannot describe anything.
commit 10d707f35f42d68d5ccaded6e98dfd84bd81b08b
Merge: 50f8664 994abf1
Author: Nima Hejazi <nhejazi@berkeley.edu>
Date:   Mon Mar 12 08:51:30 2018 -0700

    Merge pull request #119 from katrinleinweber/resolve-DOIs-securely
    
    Link DOIs to preferred resolver

==> git describe --tags --dirty <==

commit 10d707f35f42d68d5ccaded6e98dfd84bd81b08b
Merge: 50f8664 994abf1
Author: Nima Hejazi <nhejazi@berkeley.edu>
Date:   Mon Mar 12 08:51:30 2018 -0700

    Merge pull request #119 from katrinleinweber/resolve-DOIs-securely
    
    Link DOIs to preferred resolver

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working tree clean


Leaving build/test directories:
  Work:	 /opt/anaconda/anaconda3/conda-bld/skeleton_1525233478806/work 
  Test:	 /opt/anaconda/anaconda3/conda-bld/skeleton_1525233478806/test_tmp 
Leaving build/test environments:
  Test:	source activate  /opt/anaconda/anaconda3/conda-bld/skeleton_1525233478806/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
  Build:	source activate  /opt/anaconda/anaconda3/conda-bld/skeleton_1525233478806/_build_env 


Error: no tags found
```

**Comment by nhejazi** [comment]
Thanks for your interest in this! We would be happy to facilitate your providing `conda` releases of `sl3`. Is the only thing you need on our end the creation of Git tags / GitHub releases?

I'm not as familiar with `conda` as I am with language-specific package managers (e.g., `pip`) so I am just wondering whether `conda` will require that all the dependencies of `sl3` have Git tags --- do you happen to know if this is required? If so, it would make the process quite difficult.

**Comment by krinsman** [comment]
You're entirely correct; the dependencies were the bigger issue.

It's not necessary for the repository to be tagged in order to create a conda build recipe for it. The only difference is that, with the current version of `conda skeleton`, the process can only be automated when a tag exists. (And that may or may not change in later versions.)

It took a lot more time, even using the automated `conda skeleton` utility, to create the conda packages for `sl3`'s dependencies than it took to manually create a build recipe for it.

I.e. the presence of the tag would have saved about 15 minutes from a process which took ~4 hours, so all in all it doesn't seem very important (to me) at least.

Anyway, you can see the (poor-quality) build recipe I created manually for `sl3` [here](https://github.com/krinsman/r-sl3_conda-recipe), as well as [the corresponding package](https://anaconda.org/krinsman/r-sl3) uploaded to the Anaconda cloud.

This has also been done for `delayed` [(1)](https://github.com/krinsman/r-delayed_conda-recipe)[(2)](https://anaconda.org/krinsman/r-delayed) and `condensier` [(1)](https://github.com/krinsman/r-condensier_conda-recipe)[(2)](https://anaconda.org/krinsman/r-condensier).

**Comment by nhejazi** [comment]
This seems great. Thanks for your work on this! If you'd like to add a line in the `README.Rmd` to mention that there is a `conda` recipe now available, feel free to submit a PR.
