### ISSUE TITLE
where is the  Lrnr_hal9001?

### ISSUE THREAD

**Issue by EliotZhu** [tlverse/sl3#146]
The Lrnr_hal9001 base is not in the current version of sl3. Is there existing wrapper for Lrnr_hal9001 base for manual inclusion? 

Thank you.

**Comment by nhejazi** [comment]
Hello @Elio-z --- thanks for your question. In an effort to ensure stability, we have made the decision to only sparingly update the `master` branch of `sl3`. You will find that many learners and new features are present on the development branch ([`devel`](https://github.com/tlverse/sl3/tree/devel)). In particular, `Lrnr_hal9001` may be found [here](https://github.com/tlverse/sl3/blob/devel/R/Lrnr_hal9001.R). You can install the development version of `sl3`, via [`devtools`](https://CRAN.R-project.org/package=devtools) or [`remotes`](https://CRAN.R-project.org/package=remotes) like so:

```r
#remotes::install_github("tlverse/sl3@devel")
devtools::install_github("tlverse/sl3@devel")
```
