### ISSUE TITLE
what is sl3 doing with glm?     

### ISSUE THREAD

**Issue by jlstiles** [tlverse/sl3#163]
[df_ex.xlsx](https://github.com/tlverse/sl3/files/2394384/df_ex.xlsx)

There are two errors here, the first happened internally to my function, giving me this error:
```
Failed on Lrnr_glm_fast_TRUE_Cholesky
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [5] is duplicated
```
When I was debugging and used glm in place of the lrnr_glm (which had binomial outcome declared in it), there was no issue.   I will try to be more helpful in this inexplicable error in the future but it suffices to say, if glm works, why would lrnr_glm fail?  It is a situation where the outcome is taking only 4 values and when I hit unique(outcome) I actually do get a repeated value.  This makes me think somehow, these outcomes are being turned into factors and then causing the error above.  Not sure but why are factors even being created?  

For the next possibly related error:
```
devtools::install_github("tlverse/sl3")
library(sl3)
# for convenience 
install.packages("readxl")

df_ex = as.data.frame(read_xlsx("df_ex.xlsx"))
df_ex$X__1 = NULL
head(df_ex)

lrnr_glm = make_learner(Lrnr_glm, family = binomial())

task_sl <- sl3_Task$new(
  data = data.table::copy(df_ex),
  covariates = c("S", "W1", "W2"),
  outcome = "Qstar_Mg"
)

fit_sl = lrnr_glm$train(task_sl)
fit_glm = glm(Qstar_Mg ~ S + W1 + W2, data = df_ex, family = binomial())
fit_sl$coefficients
glm_fit$coef

mean(fit_sl$predict() - predict(glm_fit, type = 'response'))
```
I do see that glm and lrnr_glm are usually identical for a binary or a continuous outcome, but here they are not. I would make them always identical if possible, if they are to share the name "glm".  Thanks for checking into this!

**Comment by jeremyrcoyle** [comment]
sl3 is incorrectly detecting the outcome in your example data to be categorical (because there are only 5 unique values). You can override this as follows:

```
task_sl <- sl3_Task$new(
  data = data.table::copy(df_ex),
  covariates = c("S", "W1", "W2"),
  outcome = "Qstar_Mg",
  outcome_type="continuous"
)
```

Note that this is different than the `family` argument to `glm`/`Lrnr_glm`, and affects how `sl3` (and therefore `Lrnr_glm`) interpret the outcome.

Hopefully this resolves both of your issues, but if not feel free to reopen.

**Comment by jlstiles** [comment]
Oh right, perfect.  I'll do that, thanks.
