### ISSUE TITLE
Lrnr_stratified cannot be Stacked

### ISSUE THREAD

**Issue by nhejazi** [tlverse/sl3#171]
Based on the construction of the recently added `Lrnr_stratified`, it appears that it does not yet fully accommodate stacking, as illustrated in the following MRE:

```r
library(sl3)
mean_lrnr_strat <- Lrnr_stratified$new(lrnr = Lrnr_mean$new(), variable_stratify = "x")
fglm_lrnr_strat <- Lrnr_stratified$new(lrnr = Lrnr_glm_fast$new(), variable_stratify = "x")
lrnr_stack <- make_learner(Stack, mean_lrnr_strat, fglm_lrnr_strat)
```
which results in the following warning
```r
Warning message:
In .subset2(public_bind_env, "initialize")(...) :
  Stack has learners with identical names. This is unsupported and might lead to errors.
```

**Comment by jeremyrcoyle** [comment]
This can be fixed by overriding the `name` active member of `Lrnr_stratified` It should be something analogous to this: https://github.com/tlverse/sl3/blob/master/R/Lrnr_cv.R#L87 .
