### ISSUE TITLE
optionally print computation status

### ISSUE THREAD

**Issue by nhejazi** [tlverse/sl3#181]
In using an instantiated `Lrnr_sl` object, individual learners in the stack often print messages about their computation status; however, the end user is left with the challenge of keeping track of the status of the computation of the overall cross-validated ensemble model. It would be very helpful if `Lrnr_sl` printed which fold of its V folds was currently under training/validation to ensure the user is not left without any clues (or extra work) for long-running use-cases.

**Comment by jeremyrcoyle** [comment]
By setting `options(sl3.verbose=TRUE)` you can now get a `delayed` based progress bar that will count up the number of dependent tasks
