### ISSUE TITLE
Default learner instances

### ISSUE THREAD

**Issue by jeremyrcoyle** [tlverse/sl3#19]
Each learner should have at least one pre-instantiated version, so that users don't have to call, for example, `GLM_Learner$new()` to use the most basic version of the learner

**Comment by nhejazi** [comment]
Looks like we can also close this? Seems at odds with the current design philosophy of `sl3`, especially in that it might dis-incentivize new users from learning the `sl3` grammar fully (I mean, why would you if you can just use pre-instantiated learners without doing so?)

**Comment by jeremyrcoyle** [comment]
I haven't implemented this one yet because many of the learners more or less need arguments (there's no reasonable defaults), and i'm not sure how to name the pre-instantiated learners. I'm going to close it for now.
