### ISSUE TITLE
Add grid learners for `h2o.grid` and `xgboost`

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#2]
* Add learner classes that can support grids of hypo-params for h2o and xgboost. Similar to https://github.com/osofr/gridisl/blob/master/R/ModelH2OGridLearner.R#L3-L72
and https://github.com/osofr/gridisl/blob/master/R/ModelXGBoostGridLearner.R#L67-L235

* The learner should support grid-based interface,  specifying vectors of hypo-params for grid search, similar to https://github.com/osofr/gridisl/blob/master/tests/RUnit/RUnit_tests_01b_New_Syntax.R#L17-L38

* The learner class should return `data.table` of predictions, one column per model

**Comment by jeremyrcoyle** [comment]
I think here we want to mirror mlr's metadata for hyperparameters. For learners with hyperparameters, it would be useful to represent things like valid value ranges and "default" values. That way, we don't leave it up to the user to define a grid. I don't want to have to read a methods paper on xgboost before I define a grid on its hyperparameters.

**Comment by osofr** [comment]
Agreed. It will take some time to work through all of it though. There are a lot of hyper-params and there are a lot of learners. I agree that its the right approach.

Perhaps we can borrow something from h2o approach, and their effort to unify all of `xgboost` hyper-parameters and setting their default values: https://github.com/h2oai/h2o-3/blob/master/h2o-r/h2o-package/R/xgboost.R#L84-L284

Also, no need to read methods papers on hyper-params. These things are documented pretty well at this point: https://xgboost.readthedocs.io/en/latest/parameter.html

**Comment by osofr** [comment]
#34 add grids for h2o, based on `h2o.grid`
