### ISSUE TITLE
`Lrnr_bilstm` initialization error

### ISSUE THREAD

**Issue by nhejazi** [tlverse/sl3#226]
It seems that at some point in the recent past, some kind of incompatibility (I think between the `keras` and `kerasR` packages) has arisen that has resulted in `Lrnr_bilstm` becoming broken. The relevant unit test fails and calling the first two relevant lines from its `$train` method results in
```
Browse[1]>       model <- kerasR::Sequential()
Browse[1]>       keras::bidirectional(object = model, layer = kerasR::LSTM(args$units,
...         return_sequences = TRUE
...       ),
...       input_shape = c(num_steps, num_features)
...       )
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: Please initialize `Bidirectional` layer with a `Layer` instance. You passed: <keras.layers.recurrent.LSTM object at 0x7f94e02e8a20>

Detailed traceback:
  File "/home/nsh/miniconda3/envs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/nsh/miniconda3/envs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/keras/layers/wrappers.py", line 390, in __init__
    '`Layer` instance. You passed: {input}'.format(input=layer))
```
on a freshly configured `keras` installation (via `reticulate`). From a bit of digging, I suspect this has something to do with calling `keras::bidirectional` instead of the `kerasR` equivalent of `model$add(kerasR::Bidirectional(kerasR::LSTM))` but this wasn't easily fixable. For now, I'm going to disable the unit test for this learner to continue fixing CI builds in #222.

**Comment by imalenica** [comment]
Thanks, I'll look into it.

**Comment by nhejazi** [comment]
`kerasR` has been removed from CRAN, and this learner will be retired soon
