### ISSUE TITLE
Problem downloading SL3 package

### ISSUE THREAD

**Issue by analysitsarah** [tlverse/sl3#235]
I tried to install the "SL3" package as described on your page. 

First I tried it with: install.packages("sl3"). However I got the error "Warning in install.packages: package 'sl3' is not available (for R version 3.6.1)"

Then I tried remotes::install_github("jeremyrcoyle/sl3"). But I got the following error: Error: Failed to install 'sl3' from GitHub:
  Failed to install 'delayed' from GitHub:
  (converted from warning) installation of package '/var/folders/lv/_vm49s1j39qdfb4wqy0ff9kc0000gn/T//Rtmp8d8BIO/file39993f0c17c0/delayed_0.2.1.tar.gz' had non-zero exit status

I am working in Rstudio, with the 3.6.1 version of R. 

How can I solve this issue? I would really need to install sl3 package. 

Thanks!

**Comment by analysitsarah** [comment]
Update, I still have the same issue when using a downgraded version of R...

**Comment by jeremyrcoyle** [comment]
That output indicates that the installation failed while installing the dependency package delayed. There should be more output above that indicates what when wrong when installing delayed. Can you send all the output?

**Comment by nhejazi** [comment]
You should not have to downgrade your version of R to install `sl3`. Just to point out, the package installation will surely fail (as you've noted) from the use of `install.packages("sl3")`, as this function looks only at the CRAN repository, on which `sl3` is not yet available. Secondly, to install the package using `remotes`, one should use `remotes::install_github("tlverse/sl3")` --- while it is possible that there is a fork of the package at the address `remotes::install_github("jeremyrcoyle/sl3")`, this would probably not be the version you are looking for.
