### ISSUE TITLE
set up drat repo via github http

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#26]
Setting up drat repo with an automatically compiled dev version of the package is becoming more popular (as an alternative to `install_github`). 

The package tar is added to drat repo only if all the checks have passed, thus eliminating the possibility of someone installing the development version that is in the error state.

Basic description: https://github.com/eddelbuettel/drat
Working example: https://github.com/dmlc/drat

**Comment by nhejazi** [comment]
Could be worth integrating some ideas from [this post](https://ropensci.org/blog/2015/08/04/a-drat-repository-for-ropensci/) by _rOpenSci_.

**Comment by nhejazi** [comment]
Initial attempt at setting up a `drat` archive is available [here](https://github.com/nhejazi/sl3/tree/gh-pages); still working out some minor issues.

__update:__ All issues resolved.

**Comment by nhejazi** [comment]
Probably best to set up the drat archive to update automatically using Travis -- vignette [here](https://github.com/eddelbuettel/drat/blob/master/vignettes/CombiningDratAndTravis.Rmd).

**Comment by osofr** [comment]
Thanks Nima! 

Should we merge it into main repo? For auto travis deployment (which is a really neat feature and a great reason to use drat repo), maybe we can just copy paste data.table set-up? https://github.com/Rdatatable/data.table/blob/master/.travis.yml
https://github.com/Rdatatable/data.table/blob/master/deploy.sh

Also, an interesting idea is a script for automated CRAN submissions:
https://github.com/Rdatatable/data.table/blob/master/CRAN_Release.cmd

**Comment by nhejazi** [comment]
I'm not entirely confident that I put the drat archive together correctly. I can make the relevant changes for travis and deployment (and open a PR for `master`). I sorta bypassed our PR system and pushed the drat to branch `gh-pages` (if we turn on GitHub Pages for this branch then the package tar files should be available online via jeremyrcoyle.github.io/sl3) -- as we make changes (e.g., adding new release versions), we should open PRs for that branch.

I really like the idea of automated CRAN submissions -- we should look into this when we get closer to a CRAN release (and we'll have to edit the script that the data.table group uses a bit heavily).

**Comment by jeremyrcoyle** [comment]
Any update on this issue?

**Comment by nhejazi** [comment]
There is a drat-type repo currently set up under branch `gh-pages`. I was thinking about how to automate the build process yesterday; will try to get this done this week.
