### ISSUE TITLE
 TMLE Framework with Stochastic treatment

### ISSUE THREAD

**Issue by Shafi2016** [tlverse/sl3#261]
Hello Jeremy Coyle,

This is regarding chapter 4 of our book(https://tlverse.org/tlverse-handbook/the-tmle-framework.html). I am wondering whether there is a possibility of applying tlverse R packages to TMLE framework without using the control variable. In many economics applications, we don't have control variables. Suppose, W (predictors of inflation), A (central bank policy rate to target inflation), Y (Inflation). We want to see the inflation targeting policy of Central bank and its causal impact on inflation. We can use other techniques such as Bayesian Structural Time Series (BSTS). 

Is there any possibility of doing this kind of analysis with TMLE? or extension is possible?

**Comment by Shafi2016** [comment]
I want to add a few more points to the issue, as mentioned above, after many articles on the topic.  TMLE is used to analyze data from a non-controlled experiment that makes possible effect estimation despite the presence of confounding factors. If I understood correctly, we could use TMLE with Stochastic Treatment for the policy intervention, as mentioned above. We can use tmle3shift along with others. I still do not understand one thing. How do we determine shift_val or shift parameters?. Can this shift parameters be used as an alternative policy analysis? Such as in your example of nutritional supplements, say we increase its value for a specific period, then we want to assess its impact on disease status for that specific period.

**Comment by imalenica** [comment]
Hi, thanks for your interest!

Few notes:
1. Based on what you describe in your first post (and mentioning Bayesian Structural Time Series), that sounds like a time-series type intervention. For that we have multiple parameters, one being an non-parametric analogue to interrupted time-series (assessing an impact of an intervention at time t on downstream outcome Y(t+h)), and more data-dependent parameters where the causal target parameter is defined in terms of the observed past. 

2. If it is not a dependent data setting, then indeed, a stochastic intervention at a single time point might be of interest. I recommend opening an issue on tmle3shift page managed by @nhejazi. In general, a shift value should come from subject matter knowledge; if not, you can assess the impact across a grid of shift values, and do a variable importance type analysis.

**Comment by Shafi2016** [comment]
Thanks a lot for the comments Ivana Malenica!!

We have a more like the first situation you presented in your comments above. Treatment variables in our case are discrete in time but continuous in their values ( regime-switching variable). I found the paper on “Targeted Maximum Likelihood Estimation for Dynamic and Static Longitudinal Marginal Structural Working Models.”  I think LTMLE will work in our case.

**Comment by nhejazi** [comment]
Going to close this since we do not currently support estimation of effects from longitudinal interventions in our software stack. Stochastic interventions are supported in the `tmle3shift` package, but only for the point treatment case for now. Both the `ltmle` and `stremr` R packages support stochastic interventions with general longitudinal data structures, so those may prove useful here.
