### ISSUE TITLE
Parallel Processing

### ISSUE THREAD

**Issue by jrgant** [tlverse/sl3#274]
Is parallel processing still considered experimental? The vignette seems to indicate as much, but I wanted to confirm since I'm using the sl3 package for a study.

**Comment by jeremyrcoyle** [comment]
We've used it thoroughly at this point on internal projects. I wouldn't hesitate to use it in a study, but do let us know if you run into any troubles with it.

**Comment by jrgant** [comment]
Thanks for the quick response. In that case, I'll give it a shot and file an issue if I run into any problems.

**Comment by jrgant** [comment]
Also, is it possible to feed a specific loss function to `Lrnr_sl$new()`, for instance, something like `Lrnr_sl$new(learners = mystack, metalearner = myml, loss_fun = mylossfun)`?

The print method seems always to use squared error loss, but I'm having trouble confirming that the metalearner's weights were estimated based on the loss function I attempted to provide.

**Comment by jeremyrcoyle** [comment]
the metalearner used determines the loss function used. You can use an optimizer based metalearner to optimize for a specific loss function. The `default_metalearner` function has examples of constructing such metalearners: https://github.com/tlverse/sl3/blob/master/R/default_metalearner.R

It would be better to have the risk table output on print tied to the metalearner loss, but we haven't managed to do that yet. You can manually generate the risk table for an arbitrary loss function by using the `sl_fit$cv_risk(your_loss_function)` method

**Comment by nhejazi** [comment]
This last comment about having the metalearner loss used in the print method has been addressed by #314. We're additionally planning to better document parallelization as part of #322. Can we consider this resolved?

**Comment by nhejazi** [comment]
Parallelization has now been documented in the `README` on `devel`, so closing this. Feel free to re-open if there are any remaining points to be addressed.
