### ISSUE TITLE
Checking for continuous and discrete covariates in Lrnr_gam

### ISSUE THREAD

**Issue by jrgant** [tlverse/sl3#278]
Should this condition be changed to `if (length(X_continuous) > 0 & length(X_discrete) > 0)`? Seems this part of the code is trying to build a model formula with smoothing functions applied to continuous covariates and additional terms for discrete covariates tacked on at the end.

https://github.com/tlverse/sl3/blob/af674ded6929adb50b125269518aa7b4d9ea3899/R/Lrnr_gam.R#L102

**Comment by nhejazi** [comment]
Thanks for pointing this out. That looks correct, so I've made the change in 13f31ff.
