### ISSUE TITLE
`Lrnr_hal9001` does not use weights when supplied

### ISSUE THREAD

**Issue by Larsvanderlaan** [tlverse/sl3#289]
The fit_hal function in hal9001 does not have weights as a formal function argument. Therefore when `sl3::call_with_args` is called in `call_with_args(hal9001::fit_hal, args)`, the weights argument is filtered out. This can be fixed by adding the default arguments of glmnet as accepted arguments to `sl3::call_with_args()`.

**Comment by nhejazi** [comment]
Was this handled somewhere @Larsvanderlaan? I found that the weights arguments was being dropped by `call_with_args` in `Lrnr_hal9001` and have tried to fix it in #340.
