### ISSUE TITLE
Add learners that can by-pass external CV with their own internal CV.

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#3]
Needs to work together with `cross_validate()`

**Comment by jeremyrcoyle** [comment]
I think we can do this by implementing a property (https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_randomForest.R#L25) indicating support for internal cv. CV_Learner can check this property and use internal CV if 1) internal cv is supported and 2) internal cv supports the fold structure requested by the user.

Do you have an example where this improves performance relative to using `origami` for cross-validation?

**Comment by jeremyrcoyle** [comment]
I'm still not convinced that internal CV is going to result in performance gains that make up for the complexity of having to support it. Can you write some simple benchmarks to evaluate this?

**Comment by osofr** [comment]
Is it going to result in that much additional complexity? Technically, in the simplest use case, it shouldn't be that hard to implement, right? I agree though that supporting "generic" internal CV inside a pipeline is next to impossible... I will close this issue for now and re-open if / when there are benchmarks.
