### ISSUE TITLE
Exercise 6.1 Targeted Learning in R

### ISSUE THREAD

**Issue by annsmi11** [tlverse/sl3#324]
I keep getting errors when going through Exercise 6 on step 6 (Print your Super Learner fit by calling print() with $). Here is my code so far. The current error is at the bottom of the last code chunk. 
```{r}
#0. Load the necessary libraries and data
library(data.table)
library(dplyr)
library(readr)
library(ggplot2)
library(SuperLearner)
library(origami)
library(sl3)
library(knitr)
library(kableExtra)

db_data <- url(
  "https://raw.githubusercontent.com/benkeser/sllecture/master/chspred.csv"
)
data <- read_csv(file = db_data, col_names = TRUE)
data<- data[complete.cases(data),]

# take a quick peek
head(data) %>%
  kable(digits = 4) %>%
  kableExtra:::kable_styling(fixed_thead = TRUE) %>%
  scroll_box(width = "100%", height = "300px")
```
```{r}
#create the sl3 task
data_task <- make_sl3_Task(
  data = data,
  covariates = head(colnames(data), -1),
  outcome = "mi"
)

#visualize task
data_task

#check number folds
length(data_task$folds)

#row indexes for fold 1 training
head(data_task$folds[[1]]$training_set)

#row indexes for fold 1 validation
head(data_task$folds[[1]]$validation_set)

#check if any obs part of validation set is in the training set
any(data_task$folds[[1]]$training_set %in% data_task$folds[[1]]$validation_set)
```
```{r}
#2. Make a super learner by creating library of base learners and a metalearner. Note that the outcome is binary (yes/no).

sl3_list_properties()
sl3_list_learners("binomial")


#Now that we have an idea of some learners, we can construct them using the make_learner function or the new method.
mean_learner <- Lrnr_mean$new() #This learner provides fitting procedures for intercept models. Such models predict the outcome variable simply as the mean of the outcome vector
ranger_learner <- Lrnr_ranger$new() #Random classifications forest; This learner provides fitting procedures for a fast implementation of Random Forests, particularly suited for high dimensional data
#svm_learner <- Lrnr_svm$new() #Supervised machine learning #Support vector regression #Classification or regression challenges #SVR gives us the flexibility to define how much error is acceptable in our model and will find an appropriate line (or hyperplane in higher dimensions) to fit the data. #In contrast to OLS, the objective function of SVR is to minimize the coefficients — more specifically, the l2-norm of the coefficient vector — not the squared error. 
glm_learner <- Lrnr_glm$new() #Generalized linear model (Logistic regression)
lasso_learner <- Lrnr_glmnet$new(alpha = 1)#Lasso
ridge_learner <- Lrnr_glmnet$new(alpha = 0) #Ridge Regression
enet_learner <- Lrnr_glmnet$new(alpha = 0.5) #Elastic Net
#Lasso, Ridge, and ElasticNet are all extensions of simple linear regreesion, with an additional penalty parameter that aims to minimize complexity and/or reduce the number of features used in the final model.
```
```{r}
screen_cor <- make_learner(Lrnr_screener_correlation)
glm_pipeline <- make_learner(Pipeline, screen_cor, glm_learner)
```
```{r}
#make the stack
stack <- make_learner(Stack, glm_pipeline, glm_learner, mean_learner, ranger_learner, lasso_learner, ridge_learner, enet_learner)
stack
```
```{r}
#3. Train the Super Learner on the machine learning task
sl <- Lrnr_sl$new(
  learners = stack,
  metalearner = Lrnr_nnls$new()
)
```
```{r}
#4. Obtain predicted values
sl_fit <- sl$train(data_task)
head(sl_fit)
sl_fit_summary<-sl_fit$print()
```
Error in x[seq_len(n)] : object of type 'environment' is not subsettable

**Comment by nhejazi** [comment]
I can reproduce this locally using the `master` branch

**Comment by nhejazi** [comment]
OK, so, this error seems to come from an issue (bug?) in the initialization method of `Lrnr_sl`, which requires that the input to the `learners` argument be wrapped in a `list`. In particular, both of the following work for me and return equivalent SL predictions:

pass in the learners that made up the `Stack` but as a `list`:
```
sl <- Lrnr_sl$new(
  learners = list(glm_pipeline, glm_learner, mean_learner, ranger_learner, lasso_learner, ridge_learner, enet_learner)
)
```

easier, just wrap the instantiated `stack` in a `list`:
```
sl <- Lrnr_sl$new(
  learners = list(stack)
)
```

I'm not sure why we require that the input to `learners` be a `list`, why we don't throw an error if it's not, and/or why the input can't internally be wrapped in a `list` (if it's not already). Any thoughts on this @jeremyrcoyle @rachaelvp?

**Comment by rachaelvp** [comment]
**_I do not think this is a bug._** 
The specific line that's generating this error (for me) is `head(sl_fit)`, and that error is valid. The `head` function requires as input a vector, matrix, table, data frame or function; so the error message returned by `head(sl_fit)` makes sense: "Error in x[seq_len(n)] : object of type 'environment' is not subsettable". 

— The rest of the comment is regarding the Qs about the `learners` argument for `Lrnr_sl` instantiation — 
I believe we do internally wrap learners in a list, if needed (see highlighted lines [here](https://github.com/tlverse/sl3/blob/master/R/Lrnr_sl.R#L52-L54)). Also, a `Stack` is a list, so it's is not necessary to instantiate `Lrnr_sl` with `learners = list(stack))`, when we can do it with `learners = stack`. 

I was able to fit SL and print an SL fit with all of the following instantiations of `Lrnr_sl`:
```
# type 1: learners are input as a vector
sl_type1 <- Lrnr_sl$new(
   learners = c(glm_pipeline, glm_learner, mean_learner, ranger_learner, lasso_learner, ridge_learner, enet_learner), 
   metalearner = Lrnr_nnls$new()
)
sl_type1_fit <- sl_type1$train(data_task)
sl_type1_fit$print()

# type 2: learners are input as a list
sl_type2 <- Lrnr_sl$new(
   learners = list(glm_pipeline, glm_learner, mean_learner, ranger_learner, lasso_learner, ridge_learner, enet_learner), 
   metalearner = Lrnr_nnls$new()
)
sl_type2_fit <- sl_type2$train(data_task)
sl_type2_fit$print()

# type 3: learners are input as a stack (i.e., list)
stack <- make_learner(
   Stack, 
   glm_pipeline, glm_learner, mean_learner, ranger_learner, lasso_learner, ridge_learner, enet_learner
)
sl_type3 <- Lrnr_sl$new(
   learners = stack,
   metalearner = Lrnr_nnls$new()
)
sl_type3_fit <- sl_type3$train(data_task)
sl_type3_fit$print()
```

**Comment by nhejazi** [comment]
Thanks for weighing in here @rachaelvp. This was very helpful! I'm not sure how I managed to convince myself that the issue was coming up from passing in learners as lists, but I'm now able to run the example code without issue from both the `master` and `devel` `sl3` branches. Regarding the `x[seq_len(n)]` error, I must've not caught the fact that I'd been running `head(sl_fit)`, but removing that line circumvents the error. The clarification of passing in learners to `Lrnr_sl` is also helpful; nice to see things are pretty robust to how the `learners` argument input is provided.

I'm going to go ahead and close this @annsmi11, but feel free to re-open if we missed something.

**Comment by annsmi11** [comment]
Thank you all for looking into this. I will give this a try and let you
know if I run into any issues.

Best,
Anna
