### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by martin-codes** [tlverse/sl3#331]
I tried to install sl3 from GitHub and encountered the following error. Please advise. Thank you.

> remotes::install_github("tlverse/sl3")
Skipping install of 'sl3' from a github remote, the SHA1 (a119d471) has not changed since last install.
  Use `force = TRUE` to force installation
> remotes::install_github("tlverse/sl3",force=TRUE)
Downloading GitHub repo tlverse/sl3@HEAD
√  checking for file 'C:\Users\MPH\AppData\Local\Temp\1\RtmpkP1zMz\remotes4dc421701066\tlverse-sl3-a119d47/DESCRIPTION' (411ms)
-  preparing 'sl3': (5.9s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (1.7s)
-  checking for empty or unneeded directories
-  building 'sl3_1.4.2.tar.gz'
   
Installing package into ‘C:/Users/MPH/OneDrive - FDA/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'sl3' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Warning: S3 methods 'asub.default', 'adrop.default', 'afill<-.default', 'acorn.default' were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) : 
  undefined exports: abind, asub, afill<-, adrop, acorn
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> namespaceExport
Execution halted
ERROR: lazy loading failed for package 'sl3'
* removing 'C:/Users/MPH/OneDrive - FDA/Documents/R/win-library/4.0/sl3'
* restoring previous 'C:/Users/MPH/OneDrive - FDA/Documents/R/win-library/4.0/sl3'
Error: Failed to install 'sl3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/MPH/AppData/Local/Temp/1/RtmpkP1zMz/file4dc438915a3b/sl3_1.4.2.tar.gz’ had non-zero exit status

**Comment by jeremyrcoyle** [comment]
It seems to be upset about undefined exports:

`undefined exports: abind, asub, afill<-, adrop, acorn`

These functions are not in `sl3`, but are in the `abind` package, so maybe verify that `library(abind)` works?

**Comment by andystats** [comment]
For me, the problem was alleviated by opting NOT to update packages. 
<img width="510" alt="Screen Shot 2022-06-14 at 9 30 58 AM" src="https://user-images.githubusercontent.com/11891696/173617241-235dea7a-f149-44ee-960c-5d304ca0b20d.png">
