### ISSUE TITLE
formula argument for learner clashes with formula argument of the internal learning routine (e.g. GAM)

### ISSUE THREAD

**Issue by Larsvanderlaan** [tlverse/sl3#359]
The gam function also has a formula argument. When passing a formula through args to Lrnr_gam, the task$X input is changed according to this formula. However, the formula argument remains in self$params and gets fed to the learning routine gam.fit. Since gam uses specialized formulas, this leads to an error.

Should we remove the formula from self$params if it is provided? 

Maybe change the argument name to sl3_formula or something so that "formula" can still be passed to internal fitting functions if desired.

**Comment by nhejazi** [comment]
This is an edge case worth thinking more about for the formula functionality -- beyond just the simple bug fix in this case, what's our strategy for integrating `sl3` formulas with learners that already support their own native formula syntax @rachaelvp?

**Comment by rachaelvp** [comment]
Hi @nhejazi and @Larsvanderlaan

The formula functionality that's defined in `Lrnr_base`(https://github.com/tlverse/sl3/blob/devel/R/Lrnr_base.R#L300-L338) should be overwritten when the learner accepts a formula. It's pretty simple and here's how that's done in Lrnr_gam: https://github.com/tlverse/sl3/blob/devel/R/Lrnr_gam.R#L75-L77.

I am not getting an error like what you mentioned @Larsvanderlaan. Maybe the update to formula fixed that?  I added another test for `Lrnr_gam`, where I specify a more complex formula in `Lrnr_gam` to make sure the correct formula is being used. Here's that test: https://github.com/tlverse/sl3/blob/devel/tests/testthat/test-gam.R#L51-L65.
