### ISSUE TITLE
wrapper function for SuperLearner

### ISSUE THREAD

**Issue by jeremyrcoyle** [tlverse/sl3#38]
A nice function that does everything the current SuperLearner function does. Something for more novice users that don't want to worry about R6 and pipelines and such.

**Comment by nhejazi** [comment]
Appears that #76 will address this, among other things.

**Comment by nhejazi** [comment]
Maybe we can close this? Over various meetings/conversations, I think we've decided implementing this functionality to be outside the scope of our current design goals.

**Comment by jeremyrcoyle** [comment]
Yeah, trying to match argument-for-argument the SuperLearner::SuperLearner function is not a good use of our time. That said, I think we need to invest some time into a set of functions to make things a bit easier for novice users, both for fitting SuperLearners and in general. If we close this issue, let's make another one that's focused on that more general goal.

**Comment by jeremyrcoyle** [comment]
I think the spirit of this is better captured by https://github.com/tlverse/sl3/issues/122
