### ISSUE TITLE
sl3_Task: proper handling of outcome=NULL or allow missing outcome

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#40]
Learner task does not have to include an outcome column. For example, for true prediction with last learner in the pipeline there might be no outcomes available (e.g., new subjects with unlabelled outcomes). The prediction routine doesn't really care if there are outcomes. However, `sl3_Task` currently requires that the outcome node is provided to the constructor:
```
newtask <- sl3_Task$new(data.table(val = rep(1,20)), covariates = "val")
```

`Error in .subset2(public_bind_env, "initialize")(...) : 
  argument "outcome" is missing, with no default`

Specifying `NULL` outcome works fine, but may lead to a downstream error if the outcome were to be requested by accident:
```
newtask <- sl3_Task$new(data.table(val = rep(1,20)), covariates = "val", outcome = NULL)
newtask$Y
```

`Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index`

We should come up with a better handling for this. Perhaps add extra check in sl3_Task$Y? Maybe allow missing(outcome) in new, in which case its always set to `NULL`?

**Comment by jeremyrcoyle** [comment]
Somewhat addressed in https://github.com/jeremyrcoyle/sl3/pull/72. `task$Y` for NULL outcome generates an error:

```
> task <- sl3_Task$new(cpp, covariates = covars, outcome = NULL)
> task$Y
Error in generator_fun(node_name, self$nrow) : Node outcome not specified
```

I kind of like having to force `outcome=NULL` if you really want a task without an outcome. Do you think it's important to be able to allowing `missing(outcome)`?

**Comment by osofr** [comment]
I think so. I think it might be relevant for prediction, which I imagine would be a typical use-case of the package. So I feed a trained sl3 learner a bunch of new data, but I now have to remember each time to set `outcome = NULL`? I feel like its too much to ask of a user to remember. On the other hand, is it difficult to add missing(outcome) check that sets it to `NULL`?

**Comment by osofr** [comment]
So, I am OK with the above error, it makes sense to me. I guess all we need is a check for `missing(outcome)`?

**Comment by jeremyrcoyle** [comment]
No it's of course super easy to add that functionality. I just thought we might want to provide some signal to a user that they didn't specify an outcome so they're not surprised later. If you don't think that's necessary I'll go ahead and support missing outcome

**Comment by osofr** [comment]
Awesome! Thanks. I think this is fine.

**Comment by jeremyrcoyle** [comment]
Fixed in https://github.com/jeremyrcoyle/sl3/pull/76
