### ISSUE TITLE
Poor error messaging from Lrnr_cv$new(...)$train(...)

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#54]
It is currently very hard to debug the individual learners when doing cross-validation. Effectively, `origami::cross-validate` returns nothing / provides no messages when individual learners are failing, the only message returned is this, which is quite uninformative:

```
> cv_lrn <- Lrnr_cv$new(list(lrn1, lrn2, lrn3, lrn4))$train(task_1)
Warning message:
In cross_validate(cv_train, folds, learner, task, .combine = F,  :
  All iterations resulted in errors
```

As a result, its very time consuming to debug the learners with CV. Is there any way to pass error messages from inside this function call (for example, when `getOption("sl3.verbose")==TRUE`) ?

https://github.com/jeremyrcoyle/sl3/blob/e29892838e08985e92e5910ba86439605835d95a/R/Lrnr_cv.R#L70-L74

**Comment by nhejazi** [comment]
Perhaps I misunderstand the question, but if the goal is to simply return the function where an error occurs (this would help with debugging), then one can capture the name of the calling environment (which ends up being a function name) with something like
```r
calling_fun <- as.character(stringr::str_split(deparse(sys.call(-1)), "\\(")[[1]][1])
```
and then subsequently return this as part of an error in a construct like `tryCatch`. I've had some success in debugging this way in examples like [this one](https://github.com/benkeser/survtmle/blob/master/R/glm_fast.R). Sorry if this didn't help answer the question!

**Comment by jeremyrcoyle** [comment]
Fixed in https://github.com/jeremyrcoyle/sl3/pull/56
