### ISSUE TITLE
Lrnr_cv$new() should accept list and a stack of learners

### ISSUE THREAD

**Issue by osofr** [tlverse/sl3#55]
Currently only stack is accepted. On the other hand, `Lrnr_sl$new(learners = ` can accept both, list and Stack.

**Comment by jeremyrcoyle** [comment]
I'm not sure I agree with this one. If anything I think we should make Lrnr_sl require a stack and not accept a list of learners. The way we have it set up now calling Lrnr_sl$train silently generates a stack and then calls stack.train on it, which I think is going to cause problems when we want to parallelize that stack step (dynamically generating learner training tasks makes things extra hard). Is it really so much to ask that if a user wants to cross_validate a stack, they make a stack and then make a Lrnr_cv for it?

**Comment by osofr** [comment]
Yep, I am on the same page, I was simply pointing out the inconsistency. I don't feel strongly one way or another, as long as its consistent across learners. Its a "nice to have" feature to just be able to pass along a list of learners (and then turn it into stack internally), but if you think its going to cause problems lets abandon it. 

Perhaps a simple test and an informative error message is all we need? Something like: 
```
if (is.list(lrns)) stop("please turns the input list of learners into stack by calling Stack$new(lrn1, lrn2, ..)")
```

**Comment by jeremyrcoyle** [comment]
That makes sense. I'm going to hold off on this one until I finish trying to get delayed computation working. That'll inform how important it is not nest learners in this way.

**Comment by jeremyrcoyle** [comment]
This ended up being an easy feature to add under the new `.pretrain` `.train` framework. Fixed in the above PR
