### ISSUE TITLE
Speedglm in benchmark comparison

### ISSUE THREAD

**Issue by ck37** [tlverse/sl3#92]
In the [benchmark comparison](https://github.com/jeremyrcoyle/sl3/blob/master/inst/benchmarks/SuperLearner_benchmarks.Rmd), is there a reason that speedglm is used in sl3 but not used in SuperLearner? I doubt it will affect the results much, given the improvements from delayed etc., but it would be good to at least clarify that choice in the comparison, or use SL.speedglm in SL classic if it's faster than SL.glm.

**Comment by jeremyrcoyle** [comment]
Just an oversight. You're right, it makes more sense to compare speedglm to speedglm.

**Comment by nhejazi** [comment]
Resolved by #126.
