### ISSUE TITLE
make_learner and $new() error with list arguments

### ISSUE THREAD

**Issue by nhejazi** [tlverse/sl3#97]
Instantiating a learner with additional (modifying) arguments does not appear to work when the additional arguments are passed in as a single list. For some reason, the given learner is apparently instantiated fine but in a problematic manner that causes failure when the `$train` method of the learner is invoked. The following minimal working example illustrates the problem:

```r
library(sl3)

# example data and sl3 task
data(cpp_imputed)
covars <- c("apgar1", "apgar5", "parity", "gagebrth", "mage", "meducyrs",
            "sexn")
outcome <- "haz"
task <- sl3_Task$new(cpp_imputed, covariates = covars, outcome = outcome)

# create list of additional arguments to be passed in to learner
lrnrs_args_list <- list(nbins = 5, bin_method = "equal.len", pool = FALSE)

# initialize learner in three different ways (the third is problematic)
sl_condensier_1 <- Lrnr_condensier$new(nbins = 5, bin_method = "equal.len",
                                       pool = FALSE)
sl_condensier_2 <- make_learner(Lrnr_condensier, nbins = 5,
                                bin_method = "equal.len", pool = FALSE)
sl_condensier_3 <- make_learner(Lrnr_condensier, lrnrs_args_list)

# train the 3 learners (the third line will fail)
sl_condensier_1_fit <- sl_condensier_1$train(task)
sl_condensier_2_fit <- sl_condensier_2$train(task)
sl_condensier_3_fit <- sl_condensier_3$train(task)
```

All of these calls should in principle produce the exact same learner, and it is easy to see why it might be convenient to pass in extra/additional arguments as a single (potentially pre-made) list object. It is unclear why the third line above fails. The error produced is as follows:

```r
❯ sl_condensier_3_fit <- sl_condensier_3$train(task)
Failed on Lrnr_condensier_5_20_FALSE_NA_FALSE_NULL
Error in (function (X, Y, input_data, bin_method = c("equal.mass", "equal.len",  :
  bin_method argument must be either 'equal.len', 'equal.mass' or 'dhist'
```

**Comment by jeremyrcoyle** [comment]
Implementing this functionality would make it impossible to construct a learner that takes one argument that is a list, because it would be impossible to distinguish between a list that contains all the arguments and a list that is meant as the first argument. The best way to construct a learner from a named list of arguments would be to do `do.call(make_learner, c(learner_class=Lrnr_codensier, lrnrs_args_list))`
